//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tempo2012.UI.WPF.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tempo2012.UI.WPF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to По сметката има осчетоводявания-забрана за изтриване.
        /// </summary>
        internal static string AnaliticManagerViewModel_Delete_res2 {
            get {
                return ResourceManager.GetString("AnaliticManagerViewModel_Delete_res2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сигурни ли сте, че желаете да изтриете този запис?.
        /// </summary>
        internal static string AnaliticManagerViewModel_Delete_res3 {
            get {
                return ResourceManager.GetString("AnaliticManagerViewModel_Delete_res3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предупреждение.
        /// </summary>
        internal static string AnaliticManagerViewModel_Delete_res4 {
            get {
                return ResourceManager.GetString("AnaliticManagerViewModel_Delete_res4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Записът е изтрит.
        /// </summary>
        internal static string AnaliticManagerViewModel_Delete_res5 {
            get {
                return ResourceManager.GetString("AnaliticManagerViewModel_Delete_res5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не е избрана номенклатура.
        /// </summary>
        internal static string AnaliticManagerViewModel_editdialogres1 {
            get {
                return ResourceManager.GetString("AnaliticManagerViewModel_editdialogres1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подменени стойности в дневника. Моля коригирайте и записа по ДДС&quot;.
        /// </summary>
        internal static string ContoViewModel_UpdateRelatedDds_Message {
            get {
                return ResourceManager.GetString("ContoViewModel_UpdateRelatedDds_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предупреждение.
        /// </summary>
        internal static string ContoViewModel_UpdateRelatedDds_Title {
            get {
                return ResourceManager.GetString("ContoViewModel_UpdateRelatedDds_Title", resourceCulture);
            }
        }
    }
}
