CREATE TABLE VIESG
(
  "Id" Integer NOT NULL,
  PERIOD Integer,
  NOM Integer,
  VIN VARCHAR(16),
  KOD integer,
  VINDEST VARCHAR(16),
  PERIODOP VARCHAR(10),
  FIRMAID Integer NOT NULL,
  CONSTRAINT "PK_VIESG" PRIMARY KEY ("Id")
);
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON VIESG TO  SYSDBA WITH GRANT OPTION;

CREATE GENERATOR GENERATORVIESG;
SET GENERATOR GENERATORVIESG TO 0;

SET TERM ^ ;
CREATE TRIGGER TRIGERVIESG FOR VIESG ACTIVE
BEFORE INSERT POSITION 0
AS 
BEGIN 
      new."Id" = gen_id(generatorVIESG, 1);
END^
SET TERM ; ^